export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOG_OUT="LOG_OUT"
export const LOAD_PROFILE="LOAD_PROFILE"

// export const HOME_GIFS_SUCCESS = "HOME_GIFS_SUCCESS"
// export const HOME_GIFS_FAIL = "HOME_GIFS_FAIL"
// export const HOME_GIFS_REQUEST = "HOME_GIFS_REQUEST"

// export const SEARCHED_GIFS_REQUEST = 'SEARCHED_GIFS_REQUEST'
// export const SEARCHED_GIFS_SUCCESS = 'SEARCHED_GIFS_SUCCESS'
// export const SEARCHED_GIFS_FAIL = 'SEARCHED_GIFS_FAIL'